version: 0.2
phases:
  install:
    commands:
      - cat docker/docker-compose.prod.yml
  build:
    commands:
      - sed -i -e "s/{{CODEBUILD_BUILD_NUMBER}}/$CODEBUILD_BUILD_NUMBER/g" index.html
  post_build:
    commands:
      - cat index.html
artifacts:
  files:
    - '**/*'
