version: "3.8"

services:

  nginx:
    image: celero/nginx
    build: ./nginx/
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: Docker
        awslogs-create-group: "true"
        awslogs-stream: nginx
    environment:
      - TZ=Europe/Rome
    restart: always
